name: push_to_registry
on:
  push:
    branches: [ "main" ]
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: jakobjakob/self-hoster
jobs:
  
      


